### ISSUE TITLE
CHROME_PATH environment variable undefined

### ISSUE THREAD

**Issue by robinmetral** [codechecks/lighthouse-keeper#4]
Hi and thanks again for this project!

I've tried to set up lighthouse-keeper in my CI (using Circle CI) but checks fail with this error:

```
The environment variable CHROME_PATH must be set to executable of a build of Chromium version 54.0 or later
```

I haven't set up any such environment variable in Circle CI, and I don't think this is specified in the README. Is this expected?

The checks work as expected when I run them locally.

**Comment by krzkaczor** [comment]
I think you need to install some deps first. Definately i need to improve readme for this but just for now, can u check example repo config: https://github.com/krzkaczor/lighthouse-keeper-example/blob/master/.circleci/config.yml

**Comment by robinmetral** [comment]
Aaah didn't see this example before, exactly for CircleCI too, this is great! Thanks 🙌
